export enum EBillDetailType {
  EMITIDO = "EMITIDO",
  RECIBIDO = "RECIBIDO",
}

export enum EBillPaymentType {
  FACTURA = "FACTURA",
  BOLETA_DE_VENTA = "BOLETA_DE_VENTA",
  LIQUIDACION_DE_COMPRA = "LIQUIDACION_DE_COMPRA",
  NOTA_DE_CREDITO = "NOTA_DE_CREDITO",
  NOTA_DE_DEBITO = "NOTA_DE_DEBITO",
  RECIBO_POR_HONORARIOS = "RECIBO_POR_HONORARIOS",
  NOTA_DE_CREDITO_DE_RECIBOS = "NOTA_DE_CREDITO_DE_RECIBOS",
}
