version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: POSTGRESQL
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: granjas_islas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres:/var/lib/postgresql/data

